export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS';
export const UPDATE_NOTE_IN_STORE = 'UPDATE_NOTE_IN_STORE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';

export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST';
export const FETCH_NOTES_FAILURE = 'FETCH_NOTES_FAILURE';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';

export const RECEIVE_NOTES = 'RECEIVE_NOTES';
export const SAVE_NOTES = 'SAVE_NOTES';

export const FETCH_POSITION_REQUEST = 'FETCH_POSITION_REQUEST';
export const FETCH_POSITION_FAILURE = 'FETCH_POSITION_FAILURE';
export const FETCH_POSITION_SUCCESS = 'FETCH_POSITION_SUCCESS';

export const CAMERA_PERM_RESULT = 'CAMERA_PERM_RESULT';
export const SET_CAMERA_TYPE = 'SET_CAMERA_TYPE';